media_ids:
  - media_id: gskhw4w4lm
    channel: YouTube
    name: Chris Face VSL The Gap Method Youtube Paid Ads

  - media_id: v08dlrgr7v
    channel: Facebook
    name: Chris Face VSL The Gap Method Facebook Paid Ads